### ISSUE TITLE
simplify menu to three items

### ISSUE THREAD

**Issue by simonkoehl** [future-coop/future-bonus-app#4]
put sign out somewhere else

Final menu
- Partner
- Scannen
- Konto

**Comment by benediktdertinger** [comment]
Hi @simonkoehl, why did you decide to do so? I think we should stay with 4 tabs and use Icons + Text. This is the most common pattern. By putting the Account details in its own tab we reduce clutter in the Konto screen and make it easier to find it. Also it seems like a major break if it will be only available on the Konto screen (because it won't be neccessarily expected there and it is not consistent to only show it in this tab).

Pros:
- By using 4 screens (Partner, Scannen, Konto, Account) we use the available space in the footer tab bar (which can't be used).
- We utilize expectations and stay consistent
- We separate topics into tabs
- We reduce path lengths
- We use unused space in the tab bar

**Comment by simonkoehl** [comment]
ok!
